### ISSUE TITLE
Cannot add dht11 

### ISSUE THREAD

**Issue by AlexanderStavrop** [richardzone/homeassistant-dht#112]
I have previously added the rpi_gpio library and it works just fine. I added dht in the custom_components directory, installed the libgpiod2 package and then added the following code to my configuration.yaml

```
sensor:
  - platform: dht
    sensor: DHT11
    pin: 29
    temperature_offset: 2.1
    humidity_offset: -3.2
    monitored_conditions:
      - temperature
      - humidity
```

but after adding that
- check configuration will keep scanning and not finish
- I cannot find the sensor in order to add it
- Also, loading the other entities take much more time
any ideas whats happening?
